# Generated by Django 5.2.9 on 2026-01-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender',
            name='gender',
        ),
        migrations.AddField(
            model_name='account',
            name='aadhar',
            field=models.PositiveIntegerField(default=1234567890, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.PositiveIntegerField(default=987643210),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gender',
            name='name',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
