# Generated by Django 5.2.9 on 2026-01-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_gender_gender_account_aadhar_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
